### ISSUE TITLE
Culture invariant parsing of doubles

### ISSUE THREAD

**Issue by nilsakesson** [gemstone/comtrade#2]
According to the IEEE Std C37-xxxx it says that the floating point notation is as follows [±]dd[.]dddd[E[±]ddd]. When having the computer set to a culture that has comma (,) the decimal point the reading of the config file fails due this.

The stacktrace is like this 

```
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Double.Parse(String s)
   at Gemstone.COMTRADE.AnalogChannel..ctor(String lineImage, Int32 version, Boolean targetFloatingPoint, Boolean useRelaxedValidation) in C:\dev\comtrade\src\Gemstone.COMTRADE\AnalogChannel.cs:line 161
   at Gemstone.COMTRADE.Schema.<>c__DisplayClass4_1.<.ctor>b__0(String lineImage) in C:\dev\comtrade\src\Gemstone.COMTRADE\Schema.cs:line 310
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at Gemstone.COMTRADE.Schema..ctor(String fileName, Boolean useRelaxedValidation) in C:\dev\comtrade\src\Gemstone.COMTRADE\Schema.cs:line 310
   at DisturbanceRecordingsViewer.FaultViewerTab.ReadComtradeBtn_Click(Object sender, RoutedEventArgs e) in C:\dev\DisturbanceRecordingViewer\FaultViewerTab.xaml.cs:line 453
```

From a input number in the the config file like this
![image](https://github.com/gemstone/comtrade/assets/87042707/b6871a56-4cc7-45f5-8dc5-75f1b6456218)

My suggestion is to add the CultureInfo.InvariantCulture to all doubles being parsed.

As an example in the analog channel class:

From this:
            Multiplier = double.Parse(parts[5].Trim());
            Adder = double.Parse(parts[6].Trim());
            Skew = double.Parse(parts[7].Trim());
            MinValue = double.Parse(parts[8].Trim());
            MaxValue = double.Parse(parts[9].Trim());

To this:
             Multiplier = double.Parse(parts[5].Trim(), CultureInfo.InvariantCulture);
            Adder = double.Parse(parts[6].Trim(), CultureInfo.InvariantCulture);
            Skew = double.Parse(parts[7].Trim(), CultureInfo.InvariantCulture);
            MinValue = double.Parse(parts[8].Trim(), CultureInfo.InvariantCulture);
            MaxValue = double.Parse(parts[9].Trim(), CultureInfo.InvariantCulture);

With this, all doubles are parsed with period(.) as the decimal separator.

**Comment by nilsakesson** [comment]
I also now found it in the Timestamp class for the ToString() method. It did not parse the second part of the timestamps correctly

```
double.TryParse(parts[^1], NumberStyles.Float, CultureInfo.InvariantCulture, out double seconds);
seconds += milliseconds;
parts[^1] = seconds.ToString("00.000000", CultureInfo.InvariantCulture);
```
